name: book_app_reader
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  line_awesome_icons: ^1.0.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/ani_bahcesi.jpg
    - images/antika_titanik.jpg
    - images/ask_acilari.jpg
    - images/baslangic.jpg
    - images/ben_malala.jpg
    - images/cani.jpg
    - images/dubrovski.jpg
    - images/fahrenheit_451.jpg
    - images/fareler_ve_insanlar.jpg
    - images/gocup_gidenler.jpg
    - images/kordugum.jpg
    - images/korluk.jpg
    - images/KurkManto.jpg
    - images/simyaci.jpg
    - images/yabanci.jpg
    - images/me.jpg
    - images/user1.jpg
    - images/user2.jpg
    - images/user3.jpg
    - images/user4.jpg
    - images/user5.jpg
    - images/user6.jpg
    - images/user7.jpg
    - images/user8.jpg
    - images/user9.jpg
    - images/pink.jpg
    - images/shot_1.jpg
    - images/shot_2.jpg
    - images/shot_3.jpg
    - images/shot_4.jpg
    - images/shot_5.jpg
    - images/shot_6.jpg
    - assets/biggles.jpg
    - assets/fiction.jpg
    - assets/afr1.jpg
    - assets/afr2.jpg
    - assets/afr3.jpg
    - assets/afr4.jpg
    - assets/afr5.jpg
    - images/crime.jpg
    - images/drama.jpg
    - images/fairy.jpg
    - images/fantasy.jpg
    - images/horror.jpg
    - images/killer.jpg
    - images/scifi.jpg
    - images/shrink.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-Bold.ttf
          weight: 700

    - family: UbuntuBold
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf

    - family: UbuntuRegular
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

    - family: UbuntuLight
      fonts:
        - asset: fonts/Ubuntu-Light.ttf
      
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf

    
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
